In [1]:
!pip install d2l==0.17.2

In [2]:
# Generating the Dataset
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
# Read the Dataset
def load_array(data_arrays, batch_size, is_train=True):
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [4]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 0.30235416,  0.15009932],
        [ 0.13651289,  0.35952774],
        [-0.8479122 ,  0.01700499],
        [-0.43795457,  0.7121651 ],
        [-1.131758  ,  0.5105734 ],
        [ 0.5472282 ,  1.2240222 ],
        [ 0.54498935, -0.9161587 ],
        [-0.40440843, -0.3050664 ],
        [ 0.03057218, -1.1816293 ],
        [-0.57034934,  1.9408207 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 4.282827  ],
        [ 3.2581909 ],
        [ 2.4328334 ],
        [ 0.893381  ],
        [ 0.19915973],
        [ 1.1442357 ],
        [ 8.420599  ],
        [ 4.4254694 ],
        [ 8.27744   ],
        [-3.553673  ]], dtype=float32)>)

In [5]:
# Defining the Model
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [6]:
# Initializing Model Parameters
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [7]:
# Defining the Loss Function
loss = tf.keras.losses.MeanSquaredError()

In [8]:
# Defining the Optimization Algorithm
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [9]:
# Training
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000227
epoch 2, loss 0.000109
epoch 3, loss 0.000108


In [10]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([0.0001837  0.00014782], shape=(2,), dtype=float32)
error in estimating b [-0.00073814]
